function p = setrigpath
%------------------------------------------------------------------------
% p = setrigpath
%------------------------------------------------------------------------
% 
% sets up path
% 
%------------------------------------------------------------------------
% Input Arguments:
% 	none 
% Output Arguments:
%	p	path string
%------------------------------------------------------------------------
% See also: 
%------------------------------------------------------------------------

%------------------------------------------------------------------------
%  Sharad J. Shanbhag
%	sharad.shanbhag@einstein.yu.edu
%------------------------------------------------------------------------
% Created: ??? (SJS)
%
% Revisions:
% 	2 December, 2009 (SJS): added documentation
%------------------------------------------------------------------------
% TO DO:
%------------------------------------------------------------------------

disp('Setting path for TytoLogy...')
disp('(1) for development environment (H:\Code\TytoLogy or /home/username/Code/TytoLogy)')
disp('(2) for experiment (C:\Users\TytoLogy)')	
disp('(3) for mobile (M:\Users\TytoLogy)')
disp('(4) or <enter> for automatic settings')
userin = input('selection: ')

if isempty(userin)
	userin = 4;
end

switch userin

	case 1
		c = computer;
		switch c
			case 'PCWIN'	
				p = path(labpathdef);

			case {'MAC', 'GLNXA64'}
				disp([mfilename ':setting path for un?x'])
				p = unixpathdef;
				npaths = length(p);
				for n = 1:npaths
					if exist(p{n}, 'dir')
						addpath(p{n})
					else
						disp('Invalid Path:');
						disp(['     ' p{n}]);
					end
				end
			otherwise
				error([c ' is unknown computer'])
		end


	case 3
		c = computer;
		switch c
			case 'PCWIN'	
				p = path(labpathdef);

			case {'MAC', 'GLNXA64'}
				disp([mfilename ':setting path for un?x'])
				p = unixpathdef('/Volumes/MOFONGO/Work/TytoLogy');
				npaths = length(p);
				for n = 1:npaths
					if exist(p{n}, 'dir')
						addpath(p{n})
					else
						disp('Invalid Path:');
						disp(['     ' p{n}]);
					end
				end
			otherwise
				error([c ' is unknown computer'])
		end


	case 4
		c = computer;
		switch c
			case 'PCWIN'	
				p = path(labpathdef);

			case {'MAC', 'GLNXA64'}
				disp([mfilename ':setting path for un?x'])
				p = unixpathdef;
				npaths = length(p);
				for n = 1:npaths
					if exist(p{n}, 'dir')
						addpath(p{n})
					else
						disp('Invalid Path:');
						disp(['     ' p{n}]);
					end
				end
			otherwise
				error([c ' is unknown computer'])
		end

	otherwise
		c = computer;
		switch c
			case 'PCWIN'	
				p = path(labpathdef);

			case {'MAC', 'GLNXA64'}
				disp([mfilename ':setting path for un?x'])
				p = unixpathdef;
				npaths = length(p);
				for n = 1:npaths
					if exist(p{n}, 'dir')
						addpath(p{n})
					else
						disp('Invalid Path:');
						disp(['     ' p{n}]);
					end
				end
			otherwise
				error([c ' is unknown computer'])
		end

end

%-------------------------------------------------------------------------

%-------------------------------------------------------------------------
function p = labpathdef(varargin)
if ~nargin
	labpath = 'C:\TytoLogy\'
	toolpath = 'C:\TytoLogy\toolbox\'
else
	labpath = [varargin{1} '\main\']
	toolpath = [varargin{1} '\toolbox\']
end
% 	labpath = 'C:\Users\TytoLogy\'

p = [...
%%% BEGIN ENTRIES %%%
	  'C:\TDT\ActiveX;', ...
	  [labpath ';'], ...
	  [toolpath ';'], ...
	  [toolpath 'BinaryFileToolbox;'], ...
	  [toolpath 'Audio;'], ...
	  [toolpath 'Audio\Calibration;'], ...
	  [toolpath 'Audio\FFT;'], ...
	  [toolpath 'Audio\Filter;'], ...
	  [toolpath 'Audio\Synthesis;'], ...
	  [toolpath 'Audio\Utils;'], ...
	  [toolpath 'Multiplexer;'], ...
	  [toolpath 'SpeakerLocations;'], ...
	  [toolpath 'TDT\Functions;'], ...
	  [toolpath 'TDT\Functions\InputOutput;'], ...
	  [toolpath 'TDT\Functions\PA5;'], ...
	  [toolpath 'TDT\Functions\RP;'], ...
	  [toolpath 'TDT\Functions\RX5;'], ...
	  [toolpath 'TDT\Functions\RX6;'], ...
	  [toolpath 'TDT\Functions\RX8;'], ...
	  [toolpath 'TDT\Functions\RZ5;'], ...
	  [toolpath 'TDT\Functions\Robot;'], ...
	  [toolpath 'TDT\Functions\zBUS;'], ...
	  [toolpath 'Utilities;'], ...
	  [toolpath 'RFAnalyze;'], ...
	  [toolpath 'Robot\TDTRobot;'], ...
	  [toolpath 'UIutilities;'], ...
	  [toolpath 'structdlg;'], ...
	  [toolpath 'TytoLogyTools;'], ...
	  [labpath 'Experiments\HPSearch;'],...
	  [labpath 'Experiments\HPSearch\Functions;']...
	matlabroot, '\toolbox\matlab\general;', ...
	matlabroot, '\toolbox\matlab\ops;', ...
	matlabroot, '\toolbox\matlab\lang;', ...
	matlabroot, '\toolbox\matlab\elmat;', ...
	matlabroot, '\toolbox\matlab\randfun;', ...
	matlabroot, '\toolbox\matlab\elfun;', ...
	matlabroot, '\toolbox\matlab\specfun;', ...
	matlabroot, '\toolbox\matlab\matfun;', ...
	matlabroot, '\toolbox\matlab\datafun;', ...
	matlabroot, '\toolbox\matlab\polyfun;', ...
	matlabroot, '\toolbox\matlab\funfun;', ...
	matlabroot, '\toolbox\matlab\sparfun;', ...
	matlabroot, '\toolbox\matlab\scribe;', ...
	matlabroot, '\toolbox\matlab\graph2d;', ...
	matlabroot, '\toolbox\matlab\graph3d;', ...
	matlabroot, '\toolbox\matlab\specgraph;', ...
	matlabroot, '\toolbox\matlab\graphics;', ...
	matlabroot, '\toolbox\matlab\uitools;', ...
	matlabroot, '\toolbox\matlab\strfun;', ...
	matlabroot, '\toolbox\matlab\imagesci;', ...
	matlabroot, '\toolbox\matlab\iofun;', ...
	matlabroot, '\toolbox\matlab\audiovideo;', ...
	matlabroot, '\toolbox\matlab\timefun;', ...
	matlabroot, '\toolbox\matlab\datatypes;', ...
	matlabroot, '\toolbox\matlab\verctrl;', ...
	matlabroot, '\toolbox\matlab\codetools;', ...
	matlabroot, '\toolbox\matlab\helptools;', ...
	matlabroot, '\toolbox\matlab\winfun;', ...
	matlabroot, '\toolbox\matlab\winfun\NET;', ...
	matlabroot, '\toolbox\matlab\demos;', ...
	matlabroot, '\toolbox\matlab\timeseries;', ...
	matlabroot, '\toolbox\matlab\hds;', ...
	matlabroot, '\toolbox\matlab\guide;', ...
	matlabroot, '\toolbox\matlab\plottools;', ...
	matlabroot, '\toolbox\local;', ...
	matlabroot, '\toolbox\shared\dastudio;', ...
	matlabroot, '\toolbox\matlab\datamanager;', ...
	matlabroot, '\toolbox\shared\simulink;', ...
	matlabroot, '\toolbox\shared\instrument;', ...
	matlabroot, '\toolbox\simulink\simulink;', ...
	matlabroot, '\toolbox\simulink\simulink\slresolve;', ...
	matlabroot, '\toolbox\simulink\blocks;', ...
	matlabroot, '\toolbox\simulink\components;', ...
	matlabroot, '\toolbox\simulink\fixedandfloat;', ...
	matlabroot, '\toolbox\simulink\fixedandfloat\fxpdemos;', ...
	matlabroot, '\toolbox\simulink\fixedandfloat\obsolete;', ...
	matlabroot, '\toolbox\simulink\simdemos;', ...
	matlabroot, '\toolbox\simulink\simdemos\aerospace;', ...
	matlabroot, '\toolbox\simulink\simdemos\automotive;', ...
	matlabroot, '\toolbox\simulink\simdemos\industrial;', ...
	matlabroot, '\toolbox\simulink\simdemos\simfeatures;', ...
	matlabroot, '\toolbox\simulink\simdemos\simgeneral;', ...
	matlabroot, '\toolbox\simulink\dee;', ...
	matlabroot, '\toolbox\shared\dastudio\depviewer;', ...
	matlabroot, '\toolbox\stateflow\stateflow;', ...
	matlabroot, '\toolbox\rtw\rtw;', ...
	matlabroot, '\toolbox\shared\sigbldr;', ...
	matlabroot, '\toolbox\simulink\simulink\MPlayIO;', ...
	matlabroot, '\toolbox\simulink\simulink\dataobjectwizard;', ...
	matlabroot, '\toolbox\shared\hdlshared;', ...
	matlabroot, '\toolbox\rtw\accel;', ...
	matlabroot, '\toolbox\rtw\targets\shared;', ...
	matlabroot, '\toolbox\simulink\simulink\modeladvisor;', ...
	matlabroot, '\toolbox\simulink\simulink\modeladvisor\fixpt;', ...
	matlabroot, '\toolbox\stateflow\sfdemos;', ...
	matlabroot, '\toolbox\stateflow\coder;', ...
	matlabroot, '\toolbox\rtw\targets\AUTOSAR\AUTOSAR;', ...
	matlabroot, '\toolbox\control\control;', ...
	matlabroot, '\toolbox\control\ctrlguis;', ...
	matlabroot, '\toolbox\control\ctrlobsolete;', ...
	matlabroot, '\toolbox\control\ctrlutil;', ...
	matlabroot, '\toolbox\control\ctrldemos;', ...
	matlabroot, '\toolbox\shared\slcontrollib;', ...
	matlabroot, '\toolbox\shared\controllib\engine;', ...
	matlabroot, '\toolbox\shared\controllib\engine\options;', ...
	matlabroot, '\toolbox\shared\controllib\general;', ...
	matlabroot, '\toolbox\shared\controllib\graphics;', ...
	matlabroot, '\toolbox\shared\controllib\requirements;', ...
	matlabroot, '\toolbox\curvefit\curvefit;', ...
	matlabroot, '\toolbox\curvefit\cftoolgui;', ...
	matlabroot, '\toolbox\curvefit\sftoolgui;', ...
	matlabroot, '\toolbox\shared\optimlib;', ...
	matlabroot, '\toolbox\dspblks\dspblks;', ...
	matlabroot, '\toolbox\dspblks\dspmasks;', ...
	matlabroot, '\toolbox\dspblks\dspmex;', ...
	matlabroot, '\toolbox\dspblks\dspdemos;', ...
	matlabroot, '\toolbox\shared\filterdesignlib;', ...
	matlabroot, '\toolbox\dspblks\splibmex;', ...
	matlabroot, '\toolbox\shared\system;', ...
	matlabroot, '\toolbox\shared\dspblks\dspblks;', ...
	matlabroot, '\toolbox\shared\dspblks\dspmex;', ...
	matlabroot, '\toolbox\fixedpoint\fixedpoint;', ...
	matlabroot, '\help\toolbox\dspblks\examples;', ...
	matlabroot, '\toolbox\eml\eml;', ...
	matlabroot, '\toolbox\emlcoder\emlcoder;', ...
	matlabroot, '\toolbox\emlcoder\emlcodermex;', ...
	matlabroot, '\toolbox\shared\simtargets;', ...
	matlabroot, '\toolbox\fixedpoint\fixedpointtool;', ...
	matlabroot, '\toolbox\shared\spcuilib;', ...
	matlabroot, '\toolbox\shared\siglib;', ...
	matlabroot, '\toolbox\images\colorspaces;', ...
	matlabroot, '\toolbox\images\images;', ...
	matlabroot, '\toolbox\images\imdemos;', ...
	matlabroot, '\toolbox\images\imuitools;', ...
	matlabroot, '\toolbox\images\iptformats;', ...
	matlabroot, '\toolbox\images\iptutils;', ...
	matlabroot, '\toolbox\shared\imageslib;', ...
	matlabroot, '\toolbox\slvnv\simcoverage;', ...
	matlabroot, '\toolbox\optim\optim;', ...
	matlabroot, '\toolbox\optim\optimdemos;', ...
	matlabroot, '\toolbox\shared\rptgen;', ...
	matlabroot, '\toolbox\signal\signal;', ...
	matlabroot, '\toolbox\signal\sigtools;', ...
	matlabroot, '\toolbox\signal\sptoolgui;', ...
	matlabroot, '\toolbox\signal\sigdemos;', ...
	matlabroot, '\toolbox\sl3d\sl3d;', ...
	matlabroot, '\toolbox\sl3d\sl3ddemos;', ...
	matlabroot, '\toolbox\shared\sldv;', ...
	matlabroot, '\toolbox\stats;', ...
	matlabroot, '\toolbox\shared\statslib;', ...
	matlabroot, '\toolbox\symbolic\symbolic;', ...
	matlabroot, '\toolbox\symbolic\symbolicdemos;', ...
%%% END ENTRIES %%%
	  ...
];

p = [userpath,p];
%-------------------------------------------------------------------------


%-------------------------------------------------------------------------
function p = unixpathdef(varargin)
os = computer;
[tmp, user] = system('whoami');
user = sscanf(user, '%s');
[tmp, machine] = system('hostname');
machine = sscanf(machine, '%s');
disp(['setting path for ' machine ', user ' user '...'])

if ~length(varargin)
	if strmatch(os, 'MAC')
		mainpath = ['/Users/' user '/Work/Code/TytoLogy/main'];
		toolpath = ['/Users/' user '/Work/Code/TytoLogy/toolbox'];

	elseif strmatch(os, 'GLNXA64')
		mainpath = ['/home/' user '/Code/TytoLogy/main'];
		toolpath = ['/home/' user '/Code/TytoLogy/toolbox'];
	else
		error([mfilename ': unknown computer type ' os]);
	end

else
	mainpath = [varargin{1} '/main'];
	toolpath = [varargin{1} '/toolbox'];	
end

p = {...
	  [toolpath '/'], ...
	  [toolpath '/Audio/Calibration'], ...
	  [toolpath '/Audio/FFT'], ...
	  [toolpath '/Audio/Filter'], ...
	  [toolpath '/Audio/Synthesis'], ...
	  [toolpath '/Audio/Utils'], ...
	  [toolpath '/Multiplexer'], ...
	  [toolpath '/Robot'], ...
	  [toolpath '/SpeakerLocations'], ...
	  [toolpath '/TDT/Functions'], ...
	  [toolpath '/TDT/Functions/InputOutput'], ...
	  [toolpath '/TDT/Functions/PA5'], ...
	  [toolpath '/TDT/Functions/RP'], ...
	  [toolpath '/TDT/Functions/RX5'], ...
	  [toolpath '/TDT/Functions/RX8'], ...
	  [toolpath '/TDT/Functions/Robot'], ...
	  [toolpath '/TDT/Functions/zBUS'], ...
	  [toolpath '/Utilities'], ...
	  [toolpath '/UIutilities'], ...
	  [toolpath '/RFAnalyze'], ...
	  [toolpath '/TytoLogyTools'], ...
	  [mainpath '/Calibration/MicrophoneCal'], ...
	  [mainpath '/Calibration/HeadphoneCal'], ...
	  [mainpath '/Calibration/FFCal'], ...
	  [mainpath '/Calibration/CalibrationData'], ...
	  [mainpath '/Calibration/SpeakerData'], ...
	  [mainpath '/Experiments/SpeakerMatrix'], ...
	  [mainpath '/Experiments/HPSearch'], ...
	  [mainpath '/Experiments/HPSearch/Functions'], ...
	  [mainpath '/Experiments/HPSearch/Protocols'], ...
	  [mainpath '/Experiments/RF'], ...
	  [mainpath '/Experiments/RFMPX'], ...
	  [mainpath '/Experiments/MPxMon'], ...
	  [mainpath '/Experiments/ProCell'] ...
	  [mainpath '/Experiments/RevRF;'], ...
};

% 	p = [userpath,p];
% 		  matlabroot,'/toolbox/bioinfo/bioinfo:', ...
% 		  matlabroot,'/toolbox/bioinfo/biolearning:', ...
% 		  matlabroot,'/toolbox/bioinfo/microarray:', ...
% 		  matlabroot,'/toolbox/bioinfo/mass_spec:', ...
% 		  matlabroot,'/toolbox/bioinfo/proteins:', ...
% 		  matlabroot,'/toolbox/bioinfo/biomatrices:', ...
% 		  matlabroot,'/toolbox/bioinfo/biodemos:', ...
% 		  matlabroot,'/toolbox/compiler:', ...
% 		  matlabroot,'/toolbox/curvefit/curvefit:', ...
% 		  matlabroot,'/toolbox/curvefit/cftoolgui:', ...
% 		  matlabroot,'/toolbox/images/images:', ...
% 		  matlabroot,'/toolbox/images/imuitools:', ...
% 		  matlabroot,'/toolbox/images/imdemos:', ...
% 		  matlabroot,'/toolbox/images/iptutils:', ...
% 		  matlabroot,'/toolbox/shared/imageslib:', ...
% 		  matlabroot,'/toolbox/images/medformats:', ...
% 		  matlabroot,'/toolbox/pde:', ...
% 		  matlabroot,'/toolbox/splines:', ...
% 		  matlabroot,'/toolbox/wavelet/wavelet:', ...
% 		  matlabroot,'/toolbox/wavelet/wavedemo:' ...
%-------------------------------------------------------------------------
	